controllers:
  hosts:
    controller-0:
      ansible_host: 192.168.50.200
    controller-1:
      ansible_host: 192.168.50.201
    controller-2:
      ansible_host: 192.168.50.202

workers:
  hosts:
    worker-0:
      ansible_host: 192.168.50.210
      podCIDR: 10.200.0.0/24
    worker-1:
      ansible_host: 192.168.50.211
      podCIDR: 10.200.1.0/24
    worker-2:
      ansible_host: 192.168.50.212
      podCIDR: 10.200.2.0/24

kubernetes:
  children:
    controllers:
    workers:
